spring:
#项目启动时创建servlet
  jersey:
    servlet:
      load-on-startup: 1

#禁止页面缓存
  thymeleaf:
    cache: false

#放行静态资源
  mvc:
    static-path-pattern: /static/**

mybatis:
#mapper文件路径
  mapper-locations: classpath:mybatis/mapper/**.xml
server:
  port: 8081

# 打印sql
logging:
  level:
    com.hp.studentsushe.dao: debug
  pattern:
    console: d{yyyy-MM-dd} %-2level %logger{50} - %msg%n























